//! Embeds every US Core StructureDefinition under `profiles/us-core/` so the
//! embedded set can never silently drift from the files on disk (the cause of a
//! prior "only 29 of 54 profiles" gap). Generates `US_CORE_PROFILE_JSON`.
use std::{env, fs, path::Path};

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let rel = "profiles/us-core";
    let dir = Path::new(&manifest).join(rel);

    let mut files: Vec<String> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read {rel}: {e}"))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|x| x.to_str()) == Some("json"))
        .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
        .collect();
    files.sort();

    let mut code = String::from(
        "/// Every US Core StructureDefinition under `profiles/us-core/`, embedded\n\
         /// at build time. Generated by build.rs — do not edit.\n\
         pub static US_CORE_PROFILE_JSON: &[&str] = &[\n",
    );
    for f in &files {
        code.push_str(&format!("    include_str!(\"{manifest}/{rel}/{f}\"),\n"));
        println!("cargo:rerun-if-changed={rel}/{f}");
    }
    code.push_str("];\n");

    let out = Path::new(&env::var("OUT_DIR").unwrap()).join("us_core_embedded.rs");
    fs::write(&out, code).unwrap();
    println!("cargo:rerun-if-changed={rel}");
}
